# Generated by Django 5.1 on 2024-08-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_parent_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='created_at',
        ),
    ]
