# Generated by Django 5.1 on 2024-08-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_userorder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='products',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
